Repository hubzero/framework, pull requests merged in 2019-03, with the labels that each got.

#540 [fix] Removing checked_out_time column from queries
  src/Content/Migration/Base.php
Labels: bug

#541 [feat] Adding `join` helpers and `clear` method
  src/Database/Exception/UnsupportedSyntaxException.php
  src/Database/Query.php
  src/Database/Syntax/Mysql.php
  src/Database/Syntax/Sqlite.php
  src/Database/Tests/QueryTest.php
Labels: enhancement

#542 [feature] Add ability to ignore conversion to DST
  src/Utility/Date.php
Labels: enhancement

#543 [refactor] Renaming JS namespace to Hubzero
  src/Document/Type/Html/Head.php
  src/Html/Builder/Behavior.php
  src/Html/Toolbar/Button/Help.php
Labels: refactor

#544 [refactor] Removing inline JS for admin paginator
  src/Pagination/Views/paginator.php
Labels: refactor

#545 [feat] Adding `confirm()` toolbar button
  src/Facades/Toolbar.php
Labels: enhancement

#552 [feat] Adding controller name to metadata
  src/Api/Doc/Generator.php
Labels: enhancement
